<template>
  <footer>
    <h6>
      Games and learning is a field of education research that studies what is learned by playing video games, and
      how the design principles, data and communities of video game play can be used to develop new learning
      environments. Video games create new social
      and cultural worlds – worlds that help people learn by integrating thinking, social interaction, and
      technology, all in service of doing things they care about.
      <br>Computers and other technologies have already changed the way students learn. Integrating games into
      education has the potential to create new and more powerful ways to learn in schools, communities and
      workplaces.
      <br>Games and learning researchers study how the social and collaborative aspects of video game play can
      create new kinds of learning communities. Researchers also study how the data generated by game play can be
      used to design the next generation
      of learning assessments.
    </h6>
    <p>
      Source: <a href="http://https://en.wikipedia.org/wiki/Games_and_learning">Games and learning
        Wikipedia</a>
    </p>
  </footer>
</template>

<script>
export default {
    name: 'HomeFooter'
}
</script>